#!/usr/bin/env node
/**
 * Start local Supabase, write .env.local (Vite overlay), seed Auth users.
 * Does not touch the linked Membership project.
 *
 *   npm run db:local
 *   npm run db:stop
 *   npm run db:reset
 */
import { createClient } from "@supabase/supabase-js";
import { existsSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const DEMO_PASSWORD = "LocalDev1";
const DEMO_USERS = [
  { email: "exec@ucsd.edu" },
  { email: "board@ucsd.edu" },
  { email: "alex.kim@ucsd.edu" },
  { email: "priya.shah@ucsd.edu" },
  { email: "jordan.patel@ucsd.edu" },
  { email: "nico.brandt@ucsd.edu" },
  { email: "casey.nguyen@ucsd.edu" },
  { email: "morgan.lee@ucsd.edu" },
  { email: "riley.chen@ucsd.edu" },
  { email: "avery.singh@ucsd.edu" },
  { email: "quinn.park@ucsd.edu" },
  { email: "taylor.brooks@ucsd.edu" },
  { email: "jamie.ortiz@ucsd.edu" },
  { email: "drew.wallace@ucsd.edu" },
  { email: "skylar.adams@ucsd.edu" },
  { email: "mina.cole@ucsd.edu" },
  { email: "luis.mendez@ucsd.edu" },
];

function cliBin() {
  const darwin = join(root, "node_modules/@supabase/cli-darwin-arm64/bin/supabase");
  if (existsSync(darwin)) return darwin;
  const npmBin = join(root, "node_modules/.bin/supabase");
  if (existsSync(npmBin)) return npmBin;
  throw new Error("Supabase CLI not found. Run npm install.");
}

function run(args, { capture = false } = {}) {
  const result = spawnSync(cliBin(), args, {
    cwd: root,
    encoding: "utf8",
    stdio: capture ? "pipe" : "inherit",
  });
  if (result.status !== 0) {
    if (capture) process.stderr.write(result.stderr || result.stdout || "");
    process.exit(result.status ?? 1);
  }
  return result.stdout ?? "";
}

function parseStatusEnv(raw) {
  const env = {};
  for (const line of raw.split("\n")) {
    const cut = line.indexOf("=");
    if (cut <= 0) continue;
    const key = line.slice(0, cut).trim();
    let value = line.slice(cut + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    env[key] = value;
  }
  return env;
}

function writeViteEnv(status) {
  const url = status.API_URL || status.SUPABASE_URL;
  const anon = status.ANON_KEY || status.SUPABASE_ANON_KEY;
  if (!url || !anon) {
    console.error("supabase status did not include API_URL / ANON_KEY:\n", status);
    process.exit(1);
  }
  const body = [
    "# Generated by npm run db:local. Gitignored. Overrides .env for Vite.",
    "# Delete this file to point the app at Membership again.",
    `VITE_SUPABASE_URL=${url}`,
    `VITE_SUPABASE_ANON_KEY=${anon}`,
    "",
  ].join("\n");
  writeFileSync(join(root, ".env.local"), body);
  return { url, anon, service: status.SERVICE_ROLE_KEY || status.SUPABASE_SERVICE_ROLE_KEY };
}

async function seedAuth(url, serviceRole) {
  if (!serviceRole) {
    console.error("Missing SERVICE_ROLE_KEY from supabase status.");
    process.exit(1);
  }
  const admin = createClient(url, serviceRole, {
    auth: { autoRefreshToken: false, persistSession: false },
  });

  for (const user of DEMO_USERS) {
    const { error } = await admin.auth.admin.createUser({
      email: user.email,
      password: DEMO_PASSWORD,
      email_confirm: true,
    });
    if (error && !/already|registered|exists/i.test(error.message)) {
      console.error(`Failed to create ${user.email}:`, error.message);
      process.exit(1);
    }
  }
}

const args = new Set(process.argv.slice(2));

if (args.has("--stop")) {
  run(["stop"]);
  console.log("Local Supabase stopped. Delete .env.local to use Membership in Vite again.");
  process.exit(0);
}

if (args.has("--reset")) {
  run(["db", "reset"]);
} else if (!args.has("--auth-only")) {
  run(["start"]);
}

const status = parseStatusEnv(run(["status", "-o", "env"], { capture: true }));
const { url, service } = writeViteEnv(status);
await seedAuth(url, service);

console.log(`
Local Supabase is ready (Membership was not changed).

  Studio:  http://127.0.0.1:54323
  API:     ${url}

Sign in at http://localhost:5173/?subdomain=members
  exec@ucsd.edu   / ${DEMO_PASSWORD}   (Executive)
  board@ucsd.edu  / ${DEMO_PASSWORD}   (Board)
  Other dummy board emails are in supabase/seed.sql (same password).
  Check-in code for the live dummy event: LEETCODE

Then open /sprints
`);
