-- BoardTeams: admin-editable committee catalog for the public /board page.
-- Run once in Supabase SQL Editor (or via migration) before relying on the new admin tab.
--
-- Soft-delete via deleted=true (same pattern as Events/Members).
-- Public board + member edit dropdowns only use non-deleted rows.
-- Re-running seed is safe: ON CONFLICT (team_key) DO NOTHING.

create table if not exists public."BoardTeams" (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  team_key text not null,
  label text not null,
  description text not null default '',
  sort_order integer not null default 100,
  deleted boolean not null default false,
  constraint boardteams_team_key_key unique (team_key)
);

create index if not exists boardteams_deleted_sort_idx
  on public."BoardTeams" (deleted, sort_order);

alter table public."BoardTeams" enable row level security;

drop policy if exists "BoardTeams: public read" on public."BoardTeams";
create policy "BoardTeams: public read"
  on public."BoardTeams"
  for select
  using (true);

drop policy if exists "BoardTeams: authenticated insert" on public."BoardTeams";
create policy "BoardTeams: authenticated insert"
  on public."BoardTeams"
  for insert
  to authenticated
  with check (true);

drop policy if exists "BoardTeams: authenticated update" on public."BoardTeams";
create policy "BoardTeams: authenticated update"
  on public."BoardTeams"
  for update
  to authenticated
  using (true)
  with check (true);

comment on table public."BoardTeams" is
  'Committee catalog for /board tabs and admin member team assignments.';

comment on column public."BoardTeams".team_key is
  'Stable storage key used in Members.teams JSON (e.g. OPEN_SOURCE).';

-- Seed from historical teams.json (+ Design from COMMITTEE_TYPES).
insert into public."BoardTeams" (team_key, label, description, sort_order)
values
  ('EXECUTIVE', 'Executive', 'Our executive team leads DS3 with vision and dedication, coordinating across all committees to fulfill our mission of fostering data science education and community at UCSD.', 10),
  ('INTERNAL', 'Internal', 'Our internal team is responsible for ensuring smooth operations within the organization, managing communications among teams and room-booking.', 20),
  ('EXTERNAL', 'External', 'The external team is responsible for growing and maintaining partner-relations for DS3, opening up opporuntunities for collaborations and sponsorships.', 30),
  ('FINANCE', 'Finance', 'The finance team is responsible for managing DS3''s budget, tracking expenses, and ensuring financial transparency. They work closely with other committees to allocate resources effectively.', 40),
  ('SOFTWARE', 'Software', 'This committee designs and maintains the DS3 website using cutting-edge technologies. They ensure our digital presence is modern, functional, and reflective of our mission while implementing best practices in web development.', 50),
  ('PROJECTS', 'Projects', 'The projects team develops various product-based machine learning, software engineering, & IoT initiatives for members to join. They mentor participants through the development of projects that can be showcased to recruiters & will follow industry-level standards for data science applications.', 60),
  ('CONSULTING', 'Consulting', 'The consulting team leads DS3''s consulting program and client engagements, coordinating scoping and delivery with partner organizations while supporting student consultants.', 70),
  ('MARKETING', 'Marketing', 'Our marketing team promotes DS3 on social media platforms like Instagram to attract new members while staying current with popular trends. They create engaging content that showcases our events and community to the wider UCSD campus.', 80),
  ('WORKSHOPS', 'Workshops', 'Our workshops team hosts interactive sessions on topics ranging from web development to GitHub to machine learning. They design and deliver hands-on learning experiences that teach audiences new technologies through engaging, practical instruction.', 90),
  ('PROFESSIONAL_EVENTS', 'Professional Events', 'This committee invites company representatives from organizations like Qualcomm and Palantir to meet with our members. They organize networking sessions, tech talks, and recruitment events that connect students with industry professionals.', 100),
  ('SOCIAL_EVENTS', 'Social Events', 'The social events team plans and coordinates gatherings like beach bonfires and other activities where members can get to know each other and connect. They foster a sense of community and belonging among DS3 members outside of technical contexts.', 110),
  ('ONLINE_CONTENT', 'Online Content', 'Our online content team creates and curates educational resources, tutorials, and articles related to data science. They develop digital content that extends our educational mission beyond in-person events, making knowledge accessible to a wider audience.', 120),
  ('DATAHACKS', 'DataHacks', 'The DataHacks team is responsible for organizing our annual hackathon. They coordinate logistics, recruit participants, and create an exciting environment where students collaborate on solving data science challenges!', 130),
  ('ADVISORS', 'Advisors', 'DS3''s advisors help guide our Board make strategic decisions and provide mentorship to our members. They are experienced professionals in the field of data science and technology, offering valuable insights and support.', 140),
  ('DESIGN', 'Design', 'The design team shapes DS3''s visual identity across the website, event materials, and social content.', 150),
  ('OPEN_SOURCE', 'Open Source', 'The open source team maintains and grows DS3 public projects and contributions.', 55)
on conflict (team_key) do nothing;
