-- Moved to versioned migrations. Do not run this file in the SQL Editor.
--
-- Up:     supabase/migrations/20260923200141_board_teams_catalog.sql
-- Apply:  npm run db:push (after supabase link), or GitHub Action with apply=true
